name: mytodo_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0" # Eğer hata alırsan bu satırı kontrol et

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter   

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.1
  table_calendar: 3.1.3
  intl: ^0.19.0
  firebase_core: ^2.24.2
  firebase_remote_config: ^4.3.8
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding1.png

