// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj-5h6NKkJFNzb446RzoSupxigw-BNf38',
    appId: '1:725689332719:web:b4af16a54b1fd817707c1a',
    messagingSenderId: '725689332719',
    projectId: 'mytodoappfron',
    authDomain: 'mytodoappfron.firebaseapp.com',
    storageBucket: 'mytodoappfron.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXLqslM-xwqu1OyuLL1_LFjaqsxw1DBKA',
    appId: '1:725689332719:android:ec923840c340ab53707c1a',
    messagingSenderId: '725689332719',
    projectId: 'mytodoappfron',
    storageBucket: 'mytodoappfron.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7__dZC2PtIa5IPt_j0DNvBlFiRBwKHJk',
    appId: '1:725689332719:ios:ae5b1506d331f105707c1a',
    messagingSenderId: '725689332719',
    projectId: 'mytodoappfron',
    storageBucket: 'mytodoappfron.firebasestorage.app',
    iosBundleId: 'com.example.mytodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7__dZC2PtIa5IPt_j0DNvBlFiRBwKHJk',
    appId: '1:725689332719:ios:ae5b1506d331f105707c1a',
    messagingSenderId: '725689332719',
    projectId: 'mytodoappfron',
    storageBucket: 'mytodoappfron.firebasestorage.app',
    iosBundleId: 'com.example.mytodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj-5h6NKkJFNzb446RzoSupxigw-BNf38',
    appId: '1:725689332719:web:4fa628ea959c2ead707c1a',
    messagingSenderId: '725689332719',
    projectId: 'mytodoappfron',
    authDomain: 'mytodoappfron.firebaseapp.com',
    storageBucket: 'mytodoappfron.firebasestorage.app',
  );
}
